# Run unit tests
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch:


jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Each combination of lisp and os are tested
      matrix:                 # Support more later
        lisp: [sbcl-bin]      # [sbcl-bin, ccl-bin]
        os: [ubuntu-latest]   # [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      # This action checks out our code in the working directory
      - uses: actions/checkout@v3
      
      # Run tests
      - uses: duck-systems/run-fiveam@v0
        with:
          lisp: ${{ matrix.lisp }}
          system: systems.duck.plugboard/test
          tests: :plugboard-tests
